import type { Metadata } from "next/types"
import ClientPage from "./clientpage"
import { Inter } from "next/font/google"

export const metadata: Metadata = {
  title: "Aqua Advantage",
  description: "Generated by create next app",
}

const inter = Inter({ subsets: ["latin"] })

export default function HomePage() {
  return <ClientPage />
}
